### PR TITLE
Problem: Not enough "CONNECTOR" env param example set in .env file under examples folder

### PR DESCRIPTION
**Pull request by copepen**
Issue listed here https://github.com/truflation/truflation/issues/6

### CODE REVIEW

**Comment by copepen** [comment]
@zolotokrylin could you have a look at this PR?

**Comment by zolotokrylin** [comment]
@joequant  please review. Thank you.

**Review by joequant — COMMENTED** [review]
Thanks for the comment

**Comment by joequant** [comment]
Merged commit also I addded a sample.env in examples that you can use for the kwil examples

**Pull request merged**
