### PR TITLE
feat: update kwil.py logic , create rest_to_csv connector, comment Issue in pipe_run_server.py.

### PR DESCRIPTION
**Pull request by letteldream**
Code Update

1. Updated methods for dealing with asynchronous calls to the blockchain in `kwil.py`:
- Use asyncio with aiohttp: Replace synchronous calls with asynchronous ones using the asyncio library. 
- Use async/await: Refactor methods to utilize async/await syntax for cleaner and more readable asynchronous code.

2. Improved the class structure in `kwil.py`:
- Modularization: Break down the class into smaller, more focused classes or modules to adhere to the Single Responsibility Principle.
- Error Handling: Enhance error handling to provide more meaningful error messages and handling for various scenarios.

3. Built new Connect class which pulls data from a REST interface and saving to CSV ( add simple Testscript )
4. Add comment of issue of async/await problem and package integration with asyncio in `pipeline_run_server.py`.

### CODE REVIEW

**Review by zolotokrylin — COMMENTED** [review]
Thank you for your PR.

Please rename it to comply with https://www.conventionalcommits.org/en/v1.0.0/

**Comment by joequant** [comment]
This looks good.  I will merge after doing some internal testing

**Review by joequant — APPROVED** [review]

**Comment by zolotokrylin** [comment]
@joequant can this be merged?

**Comment by joequant** [comment]
merged

**Pull request merged**
